title: Government of Icenia
email: icenia@protonmail.com
description: They work for you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iceniagov2023.protonull.uk/"
github_username:  Protonull
github_repo: IceniaGov

excerpt_separator: "<!--more-->"

# Build settings
theme: jekyll-theme-primer # Setting this explicitly so it doesn't randomly change in the future
strict_front_matter: true
future: true # Permit posts dated in the future
markdown: kramdown
plugins:
  - jekyll-redirect-from

permalink: /:year-:month-:day/:title
navigation:
  - href: /news/
    label: News
  - href: /laws/
    label: Laws
  - href: /government/borders/
    label: Borders
    target: _blank
  - href: https://discord.gg/dfwSjCjRN5
    label: Discord
    target: _blank

defaults:
  # Ensure that pages are "/name/index.html" instead of "/name.html"
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: "/:path/:basename/"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      nochin: true

keep_files:
  - /assets/css/style.css # Override style.scss from primer

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock